seeding:
  seed: 14
  rng: np.random.RandomState(0)

cleaning:
  filenames: ['/caratteristiche.xlsx', '/costi.xlsx', '/efficienza_energetica.xlsx']
  drop_cols_1: ['unità', 'Data di inizio lavori e di consegna prevista', 'Dati catastali']
  keep_cols: ['prezzo', 'informazioni catastali', 'spese condominio']
  drop_cols_2: ['numero immobili', 'offerta minima', 'rialzo minimo', 'Spesa prenota debito', 'Contributo non dovuto',
                'Tipo vendita', 'data vendita']
  subset: ['Zona', 'Superficie']
  drop_cols: ['Indirizzo', 'Immobile garantito', 'Indice prest. energetica rinnovabile',
              'Prestazione energetica del fabbricato', 'Certificazione energetica', 'Disponibilità', 'Contratto',
              'Informazioni catastali', 'Spese condominio', 'Riscaldamento', 'Efficienza energetica',
              'Riferimento e data annuncio', 'Totale piani edificio', 'Posti auto', 'Locali', 'Num_altri',
              'Num_camere_letto', 'Num_locali', 'Altre caratteristiche', 'Altre_caratteristiche', 'Data_annuncio',
              'Tipo proprietà', 'Anno di costruzione', 'Tipologia']

features:
  drop_cols: ['Prezzo_per_m2', 'Prezzo']
  target: ['Prezzo']

visualizing:
  continuous_vars: ['Prezzo', 'Superficie']
  scatter_1: 'Superficie'
  scatter_2: 'Prezzo'
  facetgrid_hue: 'Zona'
  facetgrid_var: 'Prezzo'
  corr_cols: ['Prezzo', 'Superficie', 'Num_bagni', 'Num_tot_locali', 'Posti_garage', 'Posti_esterni']

modeling:
  num_folds: 5
  scoring: 'neg_mean_squared_error'
  param_grid: {'model__n_estimators': [ 5, 20, 50, 100 ],
               'model__min_samples_split': [ 2, 8, 10 ],
               'model__max_features': [ 2, 5, 10 ]}

predicting:
 model_name: RandomForestRegressor.pkl
